							
replace cou_help = 	"AFG"  	if citizenship_iso_num_tc ==		4
replace cou_help = 	"ALA"  	if citizenship_iso_num_tc ==		248
replace cou_help = 	"ALB"  	if citizenship_iso_num_tc ==		8
replace cou_help = 	"DZA"  	if citizenship_iso_num_tc ==		12
replace cou_help = 	"ASM"  	if citizenship_iso_num_tc ==		16
replace cou_help = 	"AND"  	if citizenship_iso_num_tc ==		20
replace cou_help = 	"AGO"  	if citizenship_iso_num_tc ==		24
replace cou_help = 	"AIA"  	if citizenship_iso_num_tc ==		660
replace cou_help = 	"ATA"  	if citizenship_iso_num_tc ==		10
replace cou_help = 	"ATG"  	if citizenship_iso_num_tc ==		28
replace cou_help = 	"ARG"  	if citizenship_iso_num_tc ==		32
replace cou_help = 	"ARM"  	if citizenship_iso_num_tc ==		51
replace cou_help = 	"ABW"  	if citizenship_iso_num_tc ==		533
replace cou_help = 	"AUS"  	if citizenship_iso_num_tc ==		36
replace cou_help = 	"AUT"  	if citizenship_iso_num_tc ==		40
replace cou_help = 	"AZE"  	if citizenship_iso_num_tc ==		31
replace cou_help = 	"BHS"  	if citizenship_iso_num_tc ==		44
replace cou_help = 	"BHR"  	if citizenship_iso_num_tc ==		48
replace cou_help = 	"BGD"  	if citizenship_iso_num_tc ==		50
replace cou_help = 	"BRB"  	if citizenship_iso_num_tc ==		52
replace cou_help = 	"BLR"  	if citizenship_iso_num_tc ==		112
replace cou_help = 	"BEL"  	if citizenship_iso_num_tc ==		56
replace cou_help = 	"BLZ"  	if citizenship_iso_num_tc ==		84
replace cou_help = 	"BEN"  	if citizenship_iso_num_tc ==		204
replace cou_help = 	"BMU"  	if citizenship_iso_num_tc ==		60
replace cou_help = 	"BTN"  	if citizenship_iso_num_tc ==		64
replace cou_help = 	"BOL"  	if citizenship_iso_num_tc ==		68
replace cou_help = 	"BES"  	if citizenship_iso_num_tc ==		535
replace cou_help = 	"BIH"  	if citizenship_iso_num_tc ==		70
replace cou_help = 	"BWA"  	if citizenship_iso_num_tc ==		72
replace cou_help = 	"BVT"  	if citizenship_iso_num_tc ==		74
replace cou_help = 	"BRA"  	if citizenship_iso_num_tc ==		76
replace cou_help = 	"IOT"  	if citizenship_iso_num_tc ==		86
replace cou_help = 	"BRN"  	if citizenship_iso_num_tc ==		96
replace cou_help = 	"BGR"  	if citizenship_iso_num_tc ==		100
replace cou_help = 	"BFA"  	if citizenship_iso_num_tc ==		854
replace cou_help = 	"BDI"  	if citizenship_iso_num_tc ==		108
replace cou_help = 	"CPV"  	if citizenship_iso_num_tc ==		132
replace cou_help = 	"KHM"  	if citizenship_iso_num_tc ==		116
replace cou_help = 	"CMR"  	if citizenship_iso_num_tc ==		120
replace cou_help = 	"CAN"  	if citizenship_iso_num_tc ==		124
replace cou_help = 	"CYM"  	if citizenship_iso_num_tc ==		136
replace cou_help = 	"CAF"  	if citizenship_iso_num_tc ==		140
replace cou_help = 	"TCD"  	if citizenship_iso_num_tc ==		148
replace cou_help = 	"CHL"  	if citizenship_iso_num_tc ==		152
replace cou_help = 	"CHN"  	if citizenship_iso_num_tc ==		156
replace cou_help = 	"CXR"  	if citizenship_iso_num_tc ==		162
replace cou_help = 	"CCK"  	if citizenship_iso_num_tc ==		166
replace cou_help = 	"COL"  	if citizenship_iso_num_tc ==		170
replace cou_help = 	"COM"  	if citizenship_iso_num_tc ==		174
replace cou_help = 	"COD"  	if citizenship_iso_num_tc ==		180
replace cou_help = 	"COG"  	if citizenship_iso_num_tc ==		178
replace cou_help = 	"COK"  	if citizenship_iso_num_tc ==		184
replace cou_help = 	"CRI"  	if citizenship_iso_num_tc ==		188
replace cou_help = 	"CIV"  	if citizenship_iso_num_tc ==		384
replace cou_help = 	"HRV"  	if citizenship_iso_num_tc ==		191
replace cou_help = 	"CUB"  	if citizenship_iso_num_tc ==		192
replace cou_help = 	"CUW"  	if citizenship_iso_num_tc ==		531
replace cou_help = 	"CYP"  	if citizenship_iso_num_tc ==		196
replace cou_help = 	"CZE"  	if citizenship_iso_num_tc ==		203
replace cou_help = 	"DNK"  	if citizenship_iso_num_tc ==		208
replace cou_help = 	"DJI"  	if citizenship_iso_num_tc ==		262
replace cou_help = 	"DMA"  	if citizenship_iso_num_tc ==		212
replace cou_help = 	"DOM"  	if citizenship_iso_num_tc ==		214
replace cou_help = 	"ECU"  	if citizenship_iso_num_tc ==		218
replace cou_help = 	"EGY"  	if citizenship_iso_num_tc ==		818
replace cou_help = 	"SLV"  	if citizenship_iso_num_tc ==		222
replace cou_help = 	"GNQ"  	if citizenship_iso_num_tc ==		226
replace cou_help = 	"ERI"  	if citizenship_iso_num_tc ==		232
replace cou_help = 	"EST"  	if citizenship_iso_num_tc ==		233
replace cou_help = 	"ETH"  	if citizenship_iso_num_tc ==		231
replace cou_help = 	"FLK"  	if citizenship_iso_num_tc ==		238
replace cou_help = 	"FRO"  	if citizenship_iso_num_tc ==		234
replace cou_help = 	"FJI"  	if citizenship_iso_num_tc ==		242
replace cou_help = 	"FIN"  	if citizenship_iso_num_tc ==		246
replace cou_help = 	"FRA"  	if citizenship_iso_num_tc ==		250
replace cou_help = 	"GUF"  	if citizenship_iso_num_tc ==		254
replace cou_help = 	"PYF"  	if citizenship_iso_num_tc ==		258
replace cou_help = 	"ATF"  	if citizenship_iso_num_tc ==		260
replace cou_help = 	"GAB"  	if citizenship_iso_num_tc ==		266
replace cou_help = 	"GMB"  	if citizenship_iso_num_tc ==		270
replace cou_help = 	"GEO"  	if citizenship_iso_num_tc ==		268
replace cou_help = 	"DEU"  	if citizenship_iso_num_tc ==		276
replace cou_help = 	"GHA"  	if citizenship_iso_num_tc ==		288
replace cou_help = 	"GIB"  	if citizenship_iso_num_tc ==		292
replace cou_help = 	"GRC"  	if citizenship_iso_num_tc ==		300
replace cou_help = 	"GRL"  	if citizenship_iso_num_tc ==		304
replace cou_help = 	"GRD"  	if citizenship_iso_num_tc ==		308
replace cou_help = 	"GLP"  	if citizenship_iso_num_tc ==		312
replace cou_help = 	"GUM"  	if citizenship_iso_num_tc ==		316
replace cou_help = 	"GTM"  	if citizenship_iso_num_tc ==		320
replace cou_help = 	"GGY"  	if citizenship_iso_num_tc ==		831
replace cou_help = 	"GIN"  	if citizenship_iso_num_tc ==		324
replace cou_help = 	"GNB"  	if citizenship_iso_num_tc ==		624
replace cou_help = 	"GUY"  	if citizenship_iso_num_tc ==		328
replace cou_help = 	"HTI"  	if citizenship_iso_num_tc ==		332
replace cou_help = 	"HMD"  	if citizenship_iso_num_tc ==		334
replace cou_help = 	"VAT"  	if citizenship_iso_num_tc ==		336
replace cou_help = 	"HND"  	if citizenship_iso_num_tc ==		340
replace cou_help = 	"HKG"  	if citizenship_iso_num_tc ==		344
replace cou_help = 	"HUN"  	if citizenship_iso_num_tc ==		348
replace cou_help = 	"ISL"  	if citizenship_iso_num_tc ==		352
replace cou_help = 	"IND"  	if citizenship_iso_num_tc ==		356
replace cou_help = 	"IDN"  	if citizenship_iso_num_tc ==		360
replace cou_help = 	"IRN"  	if citizenship_iso_num_tc ==		364
replace cou_help = 	"IRQ"  	if citizenship_iso_num_tc ==		368
replace cou_help = 	"IRL"  	if citizenship_iso_num_tc ==		372
replace cou_help = 	"IMN"  	if citizenship_iso_num_tc ==		833
replace cou_help = 	"ISR"  	if citizenship_iso_num_tc ==		376
replace cou_help = 	"ITA"  	if citizenship_iso_num_tc ==		380
replace cou_help = 	"JAM"  	if citizenship_iso_num_tc ==		388
replace cou_help = 	"JPN"  	if citizenship_iso_num_tc ==		392
replace cou_help = 	"JEY"  	if citizenship_iso_num_tc ==		832
replace cou_help = 	"JOR"  	if citizenship_iso_num_tc ==		400
replace cou_help = 	"KAZ"  	if citizenship_iso_num_tc ==		398
replace cou_help = 	"KEN"  	if citizenship_iso_num_tc ==		404
replace cou_help = 	"KIR"  	if citizenship_iso_num_tc ==		296
replace cou_help = 	"PRK"  	if citizenship_iso_num_tc ==		408
replace cou_help = 	"KOR"  	if citizenship_iso_num_tc ==		410
replace cou_help = 	"KWT"  	if citizenship_iso_num_tc ==		414
replace cou_help = 	"KGZ"  	if citizenship_iso_num_tc ==		417
replace cou_help =  "KOS"   if citizenship_iso_num_tc == 		999
replace cou_help = 	"LAO"  	if citizenship_iso_num_tc ==		418
replace cou_help = 	"LVA"  	if citizenship_iso_num_tc ==		428
replace cou_help = 	"LBN"  	if citizenship_iso_num_tc ==		422
replace cou_help = 	"LSO"  	if citizenship_iso_num_tc ==		426
replace cou_help = 	"LBR"  	if citizenship_iso_num_tc ==		430
replace cou_help = 	"LBY"  	if citizenship_iso_num_tc ==		434
replace cou_help = 	"LIE"  	if citizenship_iso_num_tc ==		438
replace cou_help = 	"LTU"  	if citizenship_iso_num_tc ==		440
replace cou_help = 	"LUX"  	if citizenship_iso_num_tc ==		442
replace cou_help = 	"MAC"  	if citizenship_iso_num_tc ==		446
replace cou_help = 	"MKD"  	if citizenship_iso_num_tc ==		807
replace cou_help = 	"MDG"  	if citizenship_iso_num_tc ==		450
replace cou_help = 	"MWI"  	if citizenship_iso_num_tc ==		454
replace cou_help = 	"MYS"  	if citizenship_iso_num_tc ==		458
replace cou_help = 	"MDV"  	if citizenship_iso_num_tc ==		462
replace cou_help = 	"MLI"  	if citizenship_iso_num_tc ==		466
replace cou_help = 	"MLT"  	if citizenship_iso_num_tc ==		470
replace cou_help = 	"MHL"  	if citizenship_iso_num_tc ==		584
replace cou_help = 	"MTQ"  	if citizenship_iso_num_tc ==		474
replace cou_help = 	"MRT"  	if citizenship_iso_num_tc ==		478
replace cou_help = 	"MUS"  	if citizenship_iso_num_tc ==		480
replace cou_help = 	"MYT"  	if citizenship_iso_num_tc ==		175
replace cou_help = 	"MEX"  	if citizenship_iso_num_tc ==		484
replace cou_help = 	"FSM"  	if citizenship_iso_num_tc ==		583
replace cou_help = 	"MDA"  	if citizenship_iso_num_tc ==		498
replace cou_help = 	"MCO"  	if citizenship_iso_num_tc ==		492
replace cou_help = 	"MNG"  	if citizenship_iso_num_tc ==		496
replace cou_help = 	"MNE"  	if citizenship_iso_num_tc ==		499
replace cou_help = 	"MSR"  	if citizenship_iso_num_tc ==		500
replace cou_help = 	"MAR"  	if citizenship_iso_num_tc ==		504
replace cou_help = 	"MOZ"  	if citizenship_iso_num_tc ==		508
replace cou_help = 	"MMR"  	if citizenship_iso_num_tc ==		104
replace cou_help = 	"NAM"  	if citizenship_iso_num_tc ==		516
replace cou_help = 	"NRU"  	if citizenship_iso_num_tc ==		520
replace cou_help = 	"NPL"  	if citizenship_iso_num_tc ==		524
replace cou_help = 	"NLD"  	if citizenship_iso_num_tc ==		528
replace cou_help = 	"NCL"  	if citizenship_iso_num_tc ==		540
replace cou_help = 	"NZL"  	if citizenship_iso_num_tc ==		554
replace cou_help = 	"NIC"  	if citizenship_iso_num_tc ==		558
replace cou_help = 	"NER"  	if citizenship_iso_num_tc ==		562
replace cou_help = 	"NGA"  	if citizenship_iso_num_tc ==		566
replace cou_help = 	"NIU"  	if citizenship_iso_num_tc ==		570
replace cou_help = 	"NFK"  	if citizenship_iso_num_tc ==		574
replace cou_help = 	"MNP"  	if citizenship_iso_num_tc ==		580
replace cou_help = 	"NOR"  	if citizenship_iso_num_tc ==		578
replace cou_help = 	"OMN"  	if citizenship_iso_num_tc ==		512
replace cou_help = 	"PAK"  	if citizenship_iso_num_tc ==		586
replace cou_help = 	"PLW"  	if citizenship_iso_num_tc ==		585
replace cou_help = 	"PSE"  	if citizenship_iso_num_tc ==		275
replace cou_help = 	"PAN"  	if citizenship_iso_num_tc ==		591
replace cou_help = 	"PNG"  	if citizenship_iso_num_tc ==		598
replace cou_help = 	"PRY"  	if citizenship_iso_num_tc ==		600
replace cou_help = 	"PER"  	if citizenship_iso_num_tc ==		604
replace cou_help = 	"PHL"  	if citizenship_iso_num_tc ==		608
replace cou_help = 	"PCN"  	if citizenship_iso_num_tc ==		612
replace cou_help = 	"POL"  	if citizenship_iso_num_tc ==		616
replace cou_help = 	"PRT"  	if citizenship_iso_num_tc ==		620
replace cou_help = 	"PRI"  	if citizenship_iso_num_tc ==		630
replace cou_help = 	"QAT"  	if citizenship_iso_num_tc ==		634
replace cou_help = 	"REU"  	if citizenship_iso_num_tc ==		638
replace cou_help = 	"ROU"  	if citizenship_iso_num_tc ==		642
replace cou_help = 	"RUS"  	if citizenship_iso_num_tc ==		643
replace cou_help = 	"RWA"  	if citizenship_iso_num_tc ==		646
replace cou_help = 	"BLM"  	if citizenship_iso_num_tc ==		652
replace cou_help = 	"SHN"  	if citizenship_iso_num_tc ==		654
replace cou_help = 	"KNA"  	if citizenship_iso_num_tc ==		659
replace cou_help = 	"LCA"  	if citizenship_iso_num_tc ==		662
replace cou_help = 	"MAF"  	if citizenship_iso_num_tc ==		663
replace cou_help = 	"SPM"  	if citizenship_iso_num_tc ==		666
replace cou_help = 	"VCT"  	if citizenship_iso_num_tc ==		670
replace cou_help = 	"WSM"  	if citizenship_iso_num_tc ==		882
replace cou_help = 	"SMR"  	if citizenship_iso_num_tc ==		674
replace cou_help = 	"STP"  	if citizenship_iso_num_tc ==		678
replace cou_help = 	"SAU"  	if citizenship_iso_num_tc ==		682
replace cou_help = 	"SEN"  	if citizenship_iso_num_tc ==		686
replace cou_help = 	"SRB"  	if citizenship_iso_num_tc ==		688
replace cou_help = 	"SYC"  	if citizenship_iso_num_tc ==		690
replace cou_help = 	"SLE"  	if citizenship_iso_num_tc ==		694
replace cou_help = 	"SGP"  	if citizenship_iso_num_tc ==		702
replace cou_help = 	"SXM"  	if citizenship_iso_num_tc ==		534
replace cou_help = 	"SVK"  	if citizenship_iso_num_tc ==		703
replace cou_help = 	"SVN"  	if citizenship_iso_num_tc ==		705
replace cou_help = 	"SLB"  	if citizenship_iso_num_tc ==		90
replace cou_help = 	"SOM"  	if citizenship_iso_num_tc ==		706
replace cou_help = 	"ZAF"  	if citizenship_iso_num_tc ==		710
replace cou_help = 	"SGS"  	if citizenship_iso_num_tc ==		239
replace cou_help = 	"SSD"  	if citizenship_iso_num_tc ==		728
replace cou_help = 	"ESP"  	if citizenship_iso_num_tc ==		724
replace cou_help = 	"LKA"  	if citizenship_iso_num_tc ==		144
replace cou_help = 	"SDN"  	if citizenship_iso_num_tc ==		729
replace cou_help = 	"SUR"  	if citizenship_iso_num_tc ==		740
replace cou_help = 	"SJM"  	if citizenship_iso_num_tc ==		744
replace cou_help = 	"SWZ"  	if citizenship_iso_num_tc ==		748
replace cou_help = 	"SWE"  	if citizenship_iso_num_tc ==		752
replace cou_help = 	"CHE"  	if citizenship_iso_num_tc ==		756
replace cou_help = 	"SYR"  	if citizenship_iso_num_tc ==		760
replace cou_help = 	"TWN"  	if citizenship_iso_num_tc ==		158
replace cou_help = 	"TJK"  	if citizenship_iso_num_tc ==		762
replace cou_help = 	"TZA"  	if citizenship_iso_num_tc ==		834
replace cou_help = 	"THA"  	if citizenship_iso_num_tc ==		764
replace cou_help = 	"TLS"  	if citizenship_iso_num_tc ==		626
replace cou_help = 	"TGO"  	if citizenship_iso_num_tc ==		768
replace cou_help = 	"TKL"  	if citizenship_iso_num_tc ==		772
replace cou_help = 	"TON"  	if citizenship_iso_num_tc ==		776
replace cou_help = 	"TTO"  	if citizenship_iso_num_tc ==		780
replace cou_help = 	"TUN"  	if citizenship_iso_num_tc ==		788
replace cou_help = 	"TUR"  	if citizenship_iso_num_tc ==		792
replace cou_help = 	"TKM"  	if citizenship_iso_num_tc ==		795
replace cou_help = 	"TCA"  	if citizenship_iso_num_tc ==		796
replace cou_help = 	"TUV"  	if citizenship_iso_num_tc ==		798
replace cou_help = 	"UGA"  	if citizenship_iso_num_tc ==		800
replace cou_help = 	"UKR"  	if citizenship_iso_num_tc ==		804
replace cou_help = 	"ARE"  	if citizenship_iso_num_tc ==		784
replace cou_help = 	"GBR"  	if citizenship_iso_num_tc ==		826
replace cou_help = 	"UMI"  	if citizenship_iso_num_tc ==		581
replace cou_help = 	"USA"  	if citizenship_iso_num_tc ==		840
replace cou_help = 	"URY"  	if citizenship_iso_num_tc ==		858
replace cou_help = 	"UZB"  	if citizenship_iso_num_tc ==		860
replace cou_help = 	"VUT"  	if citizenship_iso_num_tc ==		548
replace cou_help = 	"VEN"  	if citizenship_iso_num_tc ==		862
replace cou_help = 	"VNM"  	if citizenship_iso_num_tc ==		704
replace cou_help = 	"VGB"  	if citizenship_iso_num_tc ==		92
replace cou_help = 	"VIR"  	if citizenship_iso_num_tc ==		850
replace cou_help = 	"WLF"  	if citizenship_iso_num_tc ==		876
replace cou_help = 	"ESH"  	if citizenship_iso_num_tc ==		732
replace cou_help = 	"YEM"  	if citizenship_iso_num_tc ==		887
replace cou_help = 	"ZMB"  	if citizenship_iso_num_tc ==		894
replace cou_help = 	"ZWE"  	if citizenship_iso_num_tc ==		716
